
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-rec-f25-18
owner: ucsb-cs156-f25
repo_name: proj-rec-f25-18
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"EnableShowingRequestTypesForAdmins","number":12,"title":"added create request type option on admin page","url":"https://github.com/ucsb-cs156-f25/proj-rec-f25-18/pull/12"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"fixHardcodedRequestTypes","number":11,"title":"implemented loading of hardcoded request types at application startup","url":"https://github.com/ucsb-cs156-f25/proj-rec-f25-18/pull/11"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"addRecRequestAblititytoNavBar","number":10,"title":"added link to navbar to rec page","url":"https://github.com/ucsb-cs156-f25/proj-rec-f25-18/pull/10"}]
